export const USER_LOADING = 'USER_LOADING';

export const USER_LOADED = 'USER_LOADED';

export const USER_ERROR = 'USER_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const REGISTER_FAIL = 'REGISTER_FAIL';

export const JOB_LIST_LOADING = 'JOB_LIST_LOADING';

export const JOB_LIST_LOADED = 'JOB_LIST_LOADED';

export const JOB_LIST_ERROR = 'JOB_LIST_ERROR';

export const JOB_ADDED = 'JOB_ADDED';

export const JOB_DETAIL_LOADING = 'JOB_DETAIL_LOADING';

export const JOB_DETAIL_LOADED = 'JOB_DETAIL_LOADED';

export const JOB_DETAIL_ERROR = 'JOB_DETAIL_ERROR';
